name: Kodi Addon-Check

on: [push, pull_request]

jobs:
  kodi-addon-checker:
    runs-on: ubuntu-latest
    name: Kodi addon checker
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Extract official repo target
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Kodi addon checker validation
      id: kodi-addon-checker
      uses: xbmc/action-kodi-addon-checker@v1.0
      with:
        kodi-version: ${{ steps.extract_branch.outputs.branch }}
